name: brain_reg
channels:
  - pytorch # needed for triton
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=11.8
  - numpy>=1.21.0
  - tifffile>=2023.0.0
  - opencv>=4.8.0
  - pyyaml>=6.0.0
  - scikit-image>=0.21.0
  - h5py>=3.8.0
  - pip:
    - cupy-cuda11x>=12.0.0  # Adjust version based on your CUDA version
    - triton>=2.0.0
    - torch>=2.0.0  # Required for triton 
    - tqdm